apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      name: cartservice
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: priyamomer/cartservice:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8400
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
      restartPolicy: Always