version: '3.8'

services:
  gateway:
    build: .
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      # Core Configs (unchanged)
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: Gateway
      SPRING_MAIN_WEB-APPLICATION-TYPE_ABCDEFG: reactive
      SPRING_MAIN_ALLOW-BEAN-DEFINITION-OVERRIDING: "true"

      #Eureka (unchanged)
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8761/eureka
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
      EUREKA_CLIENT_FETCH-REGISTRY: "true"
#
      # Redis (unchanged)
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379

      # OAuth2 (unchanged)
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_PROVIDER: my-provider
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-ID: GW2
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT-SECRET: GW2Secret
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_AUTHORIZATION-GRANT-TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_SCOPE: openid
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_REDIRECT-URI: http://localhost:8080/login/oauth2/code/gateway
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_ISSUER-URI: http://host.docker.internal:8000
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_AUTHORIZATION-URI: http://localhost:8000/oauth2/authorize
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MY-PROVIDER_TOKEN-URI: http://host.docker.internal:8000/oauth2/token
#
#      # Logging (unchanged)
#      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY_FILTER_RATELIMIT: DEBUG
#      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_REDIS: DEBUG
#
#      # User Service Routes
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: auth-signup-password
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/v1/auth/**
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[1]: Method=POST
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: lb://userservice
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: roles-get
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/v1/roles/**
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[1]: Method=GET
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: lb://userservice
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]: TokenRelay=
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[1]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[1]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: roles-post
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path=/v1/roles/**
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[1]: Method=POST
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: lb://userservice
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_ID: user-get
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]: Path=/v1/users/**
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[1]: Method=GET
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_URI: lb://userservice
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[0]: TokenRelay=
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[1]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[1]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_ID: user-roles-post
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_PREDICATES[0]: Path=/v1/users/**
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_PREDICATES[1]: Method=POST
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_URI: lb://userservice
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[4]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
       #Product Service Routes
#      SPRING_CLOUD_GATEWAY_ROUTES[5]_ID: "productserviceforwarding"
#      SPRING_CLOUD_GATEWAY_ROUTES[5]_PREDICATES[0]: "/v1/products/**"
#      SPRING_CLOUD_GATEWAY_ROUTES[5]_PREDICATES[1]: "GET"
#      SPRING_CLOUD_GATEWAY_ROUTES[5]_URI: "http://host.docker.internal:8090"
#      SPRING_CLOUD_GATEWAY_ROUTES[5]_FILTERS[0]: TokenRelay=

#      SPRING_CLOUD_GATEWAY_ROUTES[5]_FILTERS[1]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[5]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[5]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 3
#
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_ID: productserviceforwarding-post-patch-delete
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_PREDICATES[0]: Path=/v1/products/**
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_PREDICATES[1]: Method=POST,PATCH,DELETE
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_URI: lb://productservice
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[6]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      # Cart Service Routes
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_ID: cartservice-get
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_PREDICATES[0]: Path=/v1/cart/**
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_PREDICATES[1]: Method=GET
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_URI: lb://cartservice
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_FILTERS[0]: TokenRelay=
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_FILTERS[1]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_FILTERS[1]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[7]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_ID: cartservice-post-patch-delete
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_PREDICATES[0]: Path=/v1/cart/**
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_PREDICATES[1]: Method=POST,PATCH,DELETE
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_URI: lb://cartservice
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[8]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      # Order Service Routes
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_ID: orderservice-get
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_PREDICATES[0]: Path=/v1/orders/**
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_PREDICATES[1]: Method=GET
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_URI: lb://orderservice
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_FILTERS[0]: TokenRelay=
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_FILTERS[1]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_FILTERS[1]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[9]_FILTERS[1]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_ID: orderservice-post-patch
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_PREDICATES[0]: Path=/v1/orders/**
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_PREDICATES[1]: Method=POST,PATCH
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_URI: lb://orderservice
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[10]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      # Payment Service Routes
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_ID: paymentservice-post
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_PREDICATES[0]: Path=/v1/payments
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_PREDICATES[1]: Method=POST
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_URI: lb://paymentservice
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[11]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_ID: paymentservice-webhooks
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_PREDICATES[0]: Path=/v1/payments/webhooks
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_PREDICATES[1]: Method=POST
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_URI: lb://paymentservice
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[12]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#      # Notification Service Routes
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_ID: notificationservice-post
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_PREDICATES[0]: Path=/v1/notifications/send-message
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_PREDICATES[1]: Method=POST
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_URI: lb://notificationservice
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_FILTERS[0]_NAME: RequestRateLimiter
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_FILTERS[0]_ARGS_KEY-RESOLVER: "#{@userKeyResolver}"
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.REPLENISHRATE: 1
#      SPRING_CLOUD_GATEWAY_ROUTES[13]_FILTERS[0]_ARGS_REDIS-RATE-LIMITER.BURSTCAPACITY: 5
#
#    networks:
#      - gateway-network

networks:
  gateway-network:
    driver: bridge