apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
  labels:
    app: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  template:
    metadata:
      name: gatewayservice
      labels:
        app: gatewayservice
    spec:
      containers:
        - name: gatewayservice
          image: priyamomer/gateway:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
      restartPolicy: Always