apiVersion: v1
kind: Service
metadata:
  name: gatewayserviceservice
spec:
  selector:
    app: gatewayservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

