apiVersion: v1
kind: Service
metadata:
  name: notificationserviceservice
spec:
  selector:
    app: notificationservice
  ports:
    - protocol: TCP
      port: 8700
      targetPort: 8700
  type: LoadBalancer

