apiVersion: v1
kind: Service
metadata:
  name: paymentserviceservice
spec:
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 8600
      targetPort: 8600
  type: LoadBalancer

