apiVersion: v1
kind: Service
metadata:
  name: discoveryserviceservice
spec:
  selector:
    app: DiscoveryService
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: LoadBalancer

