apiVersion: v1
kind: Service
metadata:
  name: productserviceserviceconfig
spec:
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
  type: LoadBalancer



