global:
  scrape_interval: 15s

scrape_configs:
  # Updated eureka-discovery config
  - job_name: 'gw-monitoring'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:8761/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        regex: 'GATEWAY'
        action: 'keep'
      # Fix the hostname replacement
      - source_labels: [__address__]
        regex: 'host\.docker\.internal(:.*)'
        replacement: 'localhost${1}'
        target_label: __address__
      # Create proper instance label
      - source_labels: [__address__]
        target_label: instance



