version: '3.8'

services:
  app:
    build: .
    container_name: user-service
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/userservice
      SPRING_DATASOURCE_USERNAME: user99
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SERVER_PORT: 8000
      EUREKA: http://host.docker.internal:8761/eureka
      ELASTIC_SEARCH_URI: http://host.docker.internal:9200
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
